
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ECEN3002_Lab1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output	       [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
parameter divide_by = 12500000;
reg [9:0] ledValue;
reg [9:0] counter;
wire clock;
assign LEDR[9:0] = ledValue[9:0];


//=======================================================
//  Structural coding
//=======================================================

ECEN3002_Lab1_ClockDivider CD0 (.clock_in(CLOCK_50), .divide_by(divide_by), .reset_n(KEY[0]), .clock_out(clock));


// Flip the LEDR[0] to match the clock
always @ (posedge clock or negedge KEY[0] or negedge KEY[1])
	begin
  	if (~KEY[0])
			begin
	      ledValue <= 0;
				counter <= 0;
			end
		else if (~KEY[1])
			ledValue <= SW[9:0];
		else if (KEY[1])
			begin
	    	counter <= counter + 1;
				ledValue <= counter;
			end
    end


endmodule
