// embedded_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 711

`timescale 1 ps / 1 ps
module embedded_system_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                                    //                                                  clk_0_clk.clk
		input  wire        master_0_clk_reset_reset_bridge_in_reset_reset,                   //                   master_0_clk_reset_reset_bridge_in_reset.reset
		input  wire        reg32_avalon_interface_0_clock_reset_reset_bridge_in_reset_reset, // reg32_avalon_interface_0_clock_reset_reset_bridge_in_reset.reset
		input  wire [31:0] master_0_master_address,                                          //                                            master_0_master.address
		output wire        master_0_master_waitrequest,                                      //                                                           .waitrequest
		input  wire [3:0]  master_0_master_byteenable,                                       //                                                           .byteenable
		input  wire        master_0_master_read,                                             //                                                           .read
		output wire [31:0] master_0_master_readdata,                                         //                                                           .readdata
		output wire        master_0_master_readdatavalid,                                    //                                                           .readdatavalid
		input  wire        master_0_master_write,                                            //                                                           .write
		input  wire [31:0] master_0_master_writedata,                                        //                                                           .writedata
		output wire        reg32_avalon_interface_0_avalon_slave_0_write,                    //                    reg32_avalon_interface_0_avalon_slave_0.write
		output wire        reg32_avalon_interface_0_avalon_slave_0_read,                     //                                                           .read
		input  wire [31:0] reg32_avalon_interface_0_avalon_slave_0_readdata,                 //                                                           .readdata
		output wire [31:0] reg32_avalon_interface_0_avalon_slave_0_writedata,                //                                                           .writedata
		output wire [3:0]  reg32_avalon_interface_0_avalon_slave_0_byteenable,               //                                                           .byteenable
		output wire        reg32_avalon_interface_0_avalon_slave_0_chipselect                //                                                           .chipselect
	);

	wire         master_0_master_translator_avalon_universal_master_0_waitrequest;   // reg32_avalon_interface_0_avalon_slave_0_translator:uav_waitrequest -> master_0_master_translator:uav_waitrequest
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_readdata;      // reg32_avalon_interface_0_avalon_slave_0_translator:uav_readdata -> master_0_master_translator:uav_readdata
	wire         master_0_master_translator_avalon_universal_master_0_debugaccess;   // master_0_master_translator:uav_debugaccess -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_debugaccess
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_address;       // master_0_master_translator:uav_address -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_address
	wire         master_0_master_translator_avalon_universal_master_0_read;          // master_0_master_translator:uav_read -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_read
	wire   [3:0] master_0_master_translator_avalon_universal_master_0_byteenable;    // master_0_master_translator:uav_byteenable -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_byteenable
	wire         master_0_master_translator_avalon_universal_master_0_readdatavalid; // reg32_avalon_interface_0_avalon_slave_0_translator:uav_readdatavalid -> master_0_master_translator:uav_readdatavalid
	wire         master_0_master_translator_avalon_universal_master_0_lock;          // master_0_master_translator:uav_lock -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_lock
	wire         master_0_master_translator_avalon_universal_master_0_write;         // master_0_master_translator:uav_write -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_write
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_writedata;     // master_0_master_translator:uav_writedata -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_writedata
	wire   [2:0] master_0_master_translator_avalon_universal_master_0_burstcount;    // master_0_master_translator:uav_burstcount -> reg32_avalon_interface_0_avalon_slave_0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) master_0_master_translator (
		.clk                    (clk_0_clk_clk),                                                      //                       clk.clk
		.reset                  (reg32_avalon_interface_0_clock_reset_reset_bridge_in_reset_reset),   //                     reset.reset
		.uav_address            (master_0_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (master_0_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (master_0_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (master_0_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (master_0_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (master_0_master_byteenable),                                         //                          .byteenable
		.av_read                (master_0_master_read),                                               //                          .read
		.av_readdata            (master_0_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (master_0_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (master_0_master_write),                                              //                          .write
		.av_writedata           (master_0_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                               //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1),                                                               //               (terminated)
		.uav_response           (2'b00),                                                              //               (terminated)
		.av_response            (),                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) reg32_avalon_interface_0_avalon_slave_0_translator (
		.clk                    (clk_0_clk_clk),                                                      //                      clk.clk
		.reset                  (reg32_avalon_interface_0_clock_reset_reset_bridge_in_reset_reset),   //                    reset.reset
		.uav_address            (master_0_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (master_0_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (master_0_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_write               (reg32_avalon_interface_0_avalon_slave_0_write),                      //      avalon_anti_slave_0.write
		.av_read                (reg32_avalon_interface_0_avalon_slave_0_read),                       //                         .read
		.av_readdata            (reg32_avalon_interface_0_avalon_slave_0_readdata),                   //                         .readdata
		.av_writedata           (reg32_avalon_interface_0_avalon_slave_0_writedata),                  //                         .writedata
		.av_byteenable          (reg32_avalon_interface_0_avalon_slave_0_byteenable),                 //                         .byteenable
		.av_chipselect          (reg32_avalon_interface_0_avalon_slave_0_chipselect),                 //                         .chipselect
		.av_address             (),                                                                   //              (terminated)
		.av_begintransfer       (),                                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                                   //              (terminated)
		.av_burstcount          (),                                                                   //              (terminated)
		.av_readdatavalid       (1'b0),                                                               //              (terminated)
		.av_waitrequest         (1'b0),                                                               //              (terminated)
		.av_writebyteenable     (),                                                                   //              (terminated)
		.av_lock                (),                                                                   //              (terminated)
		.av_clken               (),                                                                   //              (terminated)
		.uav_clken              (1'b0),                                                               //              (terminated)
		.av_debugaccess         (),                                                                   //              (terminated)
		.av_outputenable        (),                                                                   //              (terminated)
		.uav_response           (),                                                                   //              (terminated)
		.av_response            (2'b00),                                                              //              (terminated)
		.uav_writeresponsevalid (),                                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                //              (terminated)
	);

endmodule
